### ISSUE TITLE
Hot-swapper does not check types of new states vs. old states

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-reactor#107]
On http://elm-lang.org/blog/Interactive-Programming.elm, it is said: "The hot-swapper can also check to see if the types of the old state matches the types of the new state, ruling out a whole class of hot-swapping-induced runtime errors."

However, that checking is not currently done by the hot-swapper, as can be seen here: https://github.com/elm-lang/core/blob/2.0.1/src/Native/Runtime.js#L449-L460 (which only compares structure, not types).

I suggest to add this issue here to the `Swapping` milestone.

**Comment by jvoigtlaender** [comment]
@vilterp (Hi, Peter), this issue belongs on the https://github.com/elm-lang/elm-reactor/milestones/Swapping list, IMHO. Evan agreed on that [here](https://github.com/elm-lang/core/issues/81#issuecomment-103058318), but somehow it still did not end up added to the milestone yet.

**Comment by vilterp** [comment]
Currently the reactor is different than what's described in the Interactive Programming post because it actually doesn't hot-swap, it only swaps. I.e. it bypasses the difficulty of verifying that the signal graph has the same structure and types by simply starting the new module from the beginning and replaying all the recorded events over it. Thus the signal graph of the new module can be completely different and we're fine (the downside is that replay time scales linearly with # events recorded).

I'm going to close this now; can come back to it if we implement real hot-swapping in reactor as opposed to replaying.

**Comment by jvoigtlaender** [comment]
But http://elm-lang.org/try *does* use hot-swapping, right? So the issue described here is real and affecting current use. I'd rather not see it left unnoticed.

One could argue that since the reactor itself does not use hot-swapping right now, the reactor repo is not the right place for this as an open issue. Well, it was once an issue opened against the `core` repo (https://github.com/elm-lang/core/issues/81), until @evancz proposed to move it over here.

So: should I reopen that other issue instead of this one?
