### ISSUE TITLE
Please provide a way to use reactor in non full screen mode

### ISSUE THREAD

**Issue by sporto** [elm-lang/elm-reactor#134]
I am attempting to integrate Rails and Elm. I want to render Elm inside a given outlet.

<img src="https://docs.google.com/drawings/d/1gQHqXKZ0AzKjPeQX26UYaiUJyQG0d1FDWP5Z8GN8eeA/pub?w=449&h=312" />

At the moment Elm `fullscreenDebug` will render the code outside the given space.

While developing using reactor is really a must, please provide a way of using it without having to go full screen.

**Comment by vilterp** [comment]
I agree that this is a necessity. Currently overhauling reactor internals; I think this shouldn't be too hard.

**Comment by vilterp** [comment]
Actually, thinking this over, I realized that it's unclear how time travel should work in the non-fullscreen case. Since Elm doesn't control the whole screen, it could only rewind the div that it lives in. This would grow more confusing if the Elm module and other javascript were interacting via ports. What do you think would be a reasonable behavior for time-travel in the non-fullscreen case?

Also, is time travel even the most valuable feature of the debugger for you, or is it watches? I'm working on making the watches better (e.g. allowing expansion of watches to see the whole history). If time travel were disabled in the non-fullscreen case (because it's unclear what it should mean) would the debugger still be useful to you just because of watches?

**Comment by sporto** [comment]
@vilterp 	Time travel is not critical at all. What is really important is just the ability to edit code and reload the page to see the changes without having to compile.

**Comment by evancz** [comment]
Tracking in #193, follow along there!
