### ISSUE TITLE
Hot swapping not working anymore?

### ISSUE THREAD

**Issue by aravantv** [elm-lang/elm-reactor#185]
That's my first time using elm so maybe it's a stupid question... But how do we activate hot swapping?
I've read in other issues that there should be a "swap" button somewhere but I don't see any such button...?

**Comment by evancz** [comment]
Sorry for the confusion. It was not possible to fit all the upgrades into Elm 0.17 so these features will be coming back in a future release.

No one had features like this when it was introduced, so we did it kind of because we *could*. In practice it wasn't ready for a more serious workflow, so the plan is to do a redesign to get the features more in line with what users need in practice.
