### ISSUE TITLE
UTF8 problems on navigation pages

### ISSUE THREAD

**Issue by lovasoa** [elm-lang/elm-reactor#189]
An erroneous encoding conversion occurs while reading the README.
My `README.md` is in UTF-8, but it is read as `ISO-8859-1` by elm.

![capture du 2016-05-22 16-45-29](https://cloud.githubusercontent.com/assets/552629/15454313/3a8bb5f4-2046-11e6-9623-46f597578d8b.png)

[README.zip](https://github.com/elm-lang/elm-reactor/files/276337/README.zip)

(The problem is that elm-reactor converts the file from `ISO-8859-1` to `UTF-8`, whereas it **already was** `UTF-8`)

**Comment by evancz** [comment]
@jvoigtlaender, is this related to your `setLocaleEncoding` change in #179?

**Comment by jvoigtlaender** [comment]
@evancz, I don't think so. I just tried cloning @lovasoa's repository to my system, and firing up version `0.16` of `elm-reactor`, and in it, opening the `elm-package.json` file (which contains the same characters in the `"summary"` field). The result is that the browser displays the same distorted characters as in @lovasoa's screenshot. Since version `0.16` of `elm-reactor` does not include my `setLocaleEncoding` change, the cause must be something else. (I assume that displaying `elm-package.json` vs. displaying `README.md` is not a relevant difference here. Version `0.16` of `elm-reactor` does not support displaying the `README`.)

Moreover, if in version `0.17` of `elm-reactor` one does not just look at the inlined `README` display on the "front page" of `elm-reactor`, but actually clicks on the `README.md` file link, that file comes up in the browser and the characters are displayed *properly*. That seems to be additional evidence that the `setLocaleEncoding` change is not at fault.

**Comment by jvoigtlaender** [comment]
Can confirm that the problem is not my change in https://github.com/elm-lang/elm-reactor/pull/179. In contrast, without that change, things are even worse. Below are screenshots made from `elm-reactor` 0.17, built from source, once with, once without the change from https://github.com/elm-lang/elm-reactor/pull/179.

First, with that change (i.e., as in the released version of `elm-reactor`):
![screen1](https://cloud.githubusercontent.com/assets/5853832/15855786/d1e91e88-2cb1-11e6-94b5-7ef14a23acc0.png)

And after clicking on the `README.md` link:
![screen2](https://cloud.githubusercontent.com/assets/5853832/15855823/06653174-2cb2-11e6-9912-1a66ed6f1825.png)

And now without the `setLocaleEncoding utf8` line:
![screen3](https://cloud.githubusercontent.com/assets/5853832/15855872/5ac5d232-2cb2-11e6-9568-14913a587853.png)
And again after clicking on the `README.md` link:
![screen4](https://cloud.githubusercontent.com/assets/5853832/15855892/7be929b4-2cb2-11e6-8421-f70dbec1b5c5.png)

Is this enough evidence that the blame must fall elsewhere?

**Comment by evancz** [comment]
Great, thanks for doing this sleuthing! Helps narrow things down a bit. I have another theory that I can test out.

**Comment by evancz** [comment]
My guess is that the root is in one of these lines:

  1. [This line](https://github.com/elm-lang/elm-reactor/blob/54437f710192c132b11e5bc016bd0e08c155191b/src/backend/Generate/Index.hs#L66) may be using `show` under the hood which fails pretty badly with certain parts of unicode. Or maybe something else that is converting the string in some way.
  - It'd be good to know if the problem already exists by [this line](https://github.com/elm-lang/elm-reactor/blob/54437f710192c132b11e5bc016bd0e08c155191b/src/backend/Generate/Index.hs#L127). Maybe add a `putStrLn` before that and see if it is messed up that early.
  - It may also be a problem with [this line](https://github.com/elm-lang/elm-reactor/blob/54437f710192c132b11e5bc016bd0e08c155191b/src/backend/Generate/Index.hs#L80) that needs to go from bytestring to string. This seems like the most promising lead right now.
  - Maybe do a `Debug.log` in the `init` function [here](https://github.com/elm-lang/elm-reactor/blob/54437f710192c132b11e5bc016bd0e08c155191b/src/pages/Index.elm#L30-L49) to see if the data is corrupted when it arrives in Elm.

I won't be able to do a ton of testing with Windows before 0.17.1 so please let me know the results if you get a chance to look into any of these!

**Comment by jvoigtlaender** [comment]
Note that the line you point to in 3. has undergone a change between 0.17 and 0.17.1, while all the above, including my testing, was based on 0.17, because 0.17.1 wasn't even pre-announced then yet (it was just in some state of `master`). The pull request that made that line change is: https://github.com/elm-lang/elm-reactor/pull/183. From its description, it looks like it was to address exactly the problem raised here. So I think the answer is that @lovasoa should simply check whether on their system 0.17.1 fixes the problem.

(I can also test on my system, but Windows being Windows, we will only really know whether the issue is fixed for OP if OP tries it on their system.)

**Comment by jvoigtlaender** [comment]
FWIW, the released 0.17.1 version (using the Windows installer) fixes all the symbols from @lovasoa's screenshot on my machine.

**Comment by lovasoa** [comment]
Yes, it's fixed for me on linux with 0.17.1.
