### ISSUE TITLE
Add a route to retreive raw JS

### ISSUE THREAD

**Issue by Warry** [elm-lang/elm-reactor#64]
[Feature request] If validated, I volunteer to develop it.

Right now, the elm-reactor only serves compiled code wrapped in HTML. Therefore, you can't use ports and 3rd party (js) libraries with it, while it does serve raw assets (images, html...). It'd be super nice to be able to load compiled code from a static html file, from which we can do whatever we want.

I suggest that we either add a brand new route, imitating the socket (e.g.: `/raw?file=Foo.elm`) or changing the `get` parameters (e.g.: `Foo.elm?raw` ; `Foo.elm?debug`). The code would then be served with the right mime-type  and when errors occur we can still append some divs in the document, e.g.:

```js
document.write("<div style=\"position:fixed; top: 0; left: 0; right: 0; max-height: 80%; padding: 20px; overflow: auto; background: #fff; border-bottom: 4px solid red; z-index: 9999;\">
  <pre>Error in Foo.elm:

Error in definition fooBar:
Could not find type 'Foo'.
  </pre>
</div>");
```

At the moment I'm using custom bash scripts, but it doesn't show the errors in the browser.

**Comment by evancz** [comment]
I do not understand the goals here.

[Here](https://github.com/elm-lang/elm-reactor#debugging-code-embedded-in-html) are the instructions on embedding the Elm code in HTML. This allows you to add custom CSS.

At the moment ports are not supported because it may not be possible to reliably provide a good user experience. There needs to be some way to make rewind and restart and swap work nicely when you have ports that have actual side-effects. I do not know the answer to this and it has been discussed in another issue.

I see that there is a feature suggestion, but I do not understand the underlying issue. Can you say it another way?

**Comment by evancz** [comment]
I'm pretty sure you can do this now, but I added it to #193 so we can be sure it's available in the next iteration.
